apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 3000
      targetPort: 3000
  type: LoadBalancer
